metadata:
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/foobargem/argocd-example.git
    targetRevision: HEAD
