apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: {{ .Values.spec.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.4
      helm:
        valueFiles:
          - $values/charts/ingress-nginx/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
