metadata:
  namespace: argo

spec:
  project: cluster-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: foo
  source:
    repoURL: https://github.com/foobargem/argocd-example.git
    targetRevision: dev-app
