apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: {{ .Values.spec.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/foo
    helm:
      releaseName: {{ .Release.Name }}
      {{- with .Values.spec.source.helm.valueFiles }}
      valueFiles:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
