apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo
spec:
  project: cluster-infra
  destination:
    name: kind
    namespace: ingress-nginx
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.4
      helm:
        valueFiles:
          - $values/charts/ingress-nginx/values.yaml
    - repoURL: https://github.com/foobargem/argocd-example.git
      targetRevision: dev
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
